language: cpp
os: windows
env: MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
install:
  - ./scripts/vcpkg.sh
script:
  - export PATH="${MSBUILD_PATH}":"${PATH}"
  - MSBuild.exe
